import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GlobalSearchBar from "../components/GlobalSearchBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <div style={{ maxWidth: 960, margin: "0 auto", padding: "16px 16px 0" }}>
          <GlobalSearchBar />
        </div>
        {children}
      </body>
    </html>
  );
}
